# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinDate', models.DateField(auto_now_add=True)),
                ('fullname', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('role', models.CharField(choices=[('F', 'Founder'), ('M', 'Member'), ('C', 'Contributor'), ('W', 'Staff Writer')], editable=False, max_length=1)),
                ('emailVerified', models.BooleanField(default=False, editable=False)),
                ('bio', models.TextField(blank=True)),
                ('facebook', models.CharField(blank=True, max_length=128)),
                ('twitter', models.CharField(blank=True, max_length=128)),
                ('tumblr', models.CharField(blank=True, max_length=128)),
                ('website', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
