# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20160530_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_style', django_mysql.models.EnumField(choices=[('informational', 'informational'), ('opinion', 'opinion')])),
                ('article_type', django_mysql.models.EnumField(choices=[('feature', 'feature'), ('regular', 'regular')])),
                ('category', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('co_author', models.CharField(blank=True, max_length=64)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cycle', models.IntegerField()),
                ('cycle_article', models.BooleanField(default=False)),
                ('description', django_mysql.models.SizedTextField(blank=True, size_class=2)),
                ('feature_image', models.ImageField(blank=True, upload_to='')),
                ('header_image', models.ImageField(blank=True, upload_to='')),
                ('photo_credit', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateTimeField(blank=True)),
                ('search_terms', django_mysql.models.SizedTextField(blank=True, size_class=2)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('status', django_mysql.models.EnumField(choices=[('published', 'published'), ('queued', 'queued'), ('ready', 'ready'), ('draft', 'draft')])),
                ('tags', django_mysql.models.SizedTextField(blank=True, size_class=2)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('status', django_mysql.models.EnumField(choices=[('pending', 'pending'), ('reviewed', 'reviewed')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('role', models.CharField(choices=[('F', 'Founder'), ('M', 'Member'), ('C', 'Contributor'), ('W', 'Staff Writer')], default='M', editable=False, max_length=1)),
                ('bio', django_mysql.models.SizedTextField(blank=True, size_class=2)),
                ('linkedin', models.CharField(blank=True, max_length=128)),
                ('pinterest', models.CharField(blank=True, max_length=128)),
                ('facebook', models.CharField(blank=True, max_length=128)),
                ('instagram', models.CharField(blank=True, max_length=128)),
                ('twitter', models.CharField(blank=True, max_length=128)),
                ('tumblr', models.CharField(blank=True, max_length=128)),
                ('website', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
