# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cycle_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='cycles', related_query_name='rotation', to='dashboard.Article'),
        ),
    ]
