# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20160603_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='descrtiption',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=django_mysql.models.SizedTextField(blank=True, size_class=2),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
