# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20160603_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subcategory',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=15), max_length=80, size=5),
        ),
    ]
