# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20160603_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='search_terms',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=36), blank=True, max_length=740, size=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=36), blank=True, max_length=740, size=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subcategory',
            field=django_mysql.models.ListCharField(models.CharField(max_length=15), blank=True, max_length=80, size=5),
        ),
    ]
