# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20160603_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='topic',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='_topic_subcategory_+', to='dashboard.Topic'),
        ),
    ]
