# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20160604_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('F', 'Founder'), ('M', 'Member'), ('C', 'Contributor'), ('W', 'Staff Writer')], default='M', max_length=1),
        ),
    ]
