# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20160618_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(blank=True, default='/static/images/avatars/nan.jpg', max_length=64),
        ),
    ]
